input {
  gelf {
    port => 12201
    use_tcp => false
  }
}

filter {
  if "api_gateway" in [message] {
    json {
      source => "message"
      remove_field => ["message", "full_message", "host", "level", "version", "short_message"]
    }

    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
  } else {
    drop {}
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cache-metrics-%{+YYYY.MM.dd}" 
  }
}