input {
  file {
    path => "/data/pig_output/tabla_eventos_enriquecidos_final/part-r-00000"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  # Procesar la línea como un CSV
  csv {
    separator => ","
    # Nombres para cada una de las 17 columnas de tu ejemplo
    columns => [
      "uuid", "pubMillis", "tipo_evento", "subtipo_evento", "latitud", "longitud", 
      "comuna", "calle", "cruce_calle", "fiabilidad", "reportes", "fecha_utc", 
      "hora", "minuto", "dia_semana_num", "anio", "dia_semana_nombre"
    ]
  }

  #  Convertir los tipos de datos de texto a números
  mutate {
    convert => { "pubMillis" => "integer" }
    convert => { "latitud" => "float" }
    convert => { "longitud" => "float" }
    convert => { "fiabilidad" => "integer" }
    convert => { "reportes" => "integer" }
    convert => { "hora" => "integer" }
    convert => { "minuto" => "integer" }
  }

  #  Crear un campo de geolocalización para usar en mapas de Kibana
  mutate {
    add_field => { "[location][lon]" => "%{longitud}" }
    add_field => { "[location][lat]" => "%{latitud}" }
    convert => { "[location][lon]" => "float" }
    convert => { "[location][lat]" => "float" }
  }

  #  Usar el timestamp 'pubMillis' como la fecha principal del evento
  date {
    match => [ "pubMillis", "UNIX_MS" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "eventos_waze" 
    document_id => "%{uuid}" 
  }
  stdout { codec => rubydebug }
}